### PR TITLE
favicon and embeds

### PR DESCRIPTION
**Pull request by g9aerospace**
check this stuff out.

### CODE REVIEW

**Comment by nxrmqlly** [comment]
Can you add .vscode/ to .gitignore please?

**Comment by nxrmqlly** [comment]
Revert back to https://github.com/nxrmqlly/nxrmqlly.github.io/pull/1/commits/9d39dff4c024d1434c3c8330fd9b1385a2b329d8 please

**Comment by nxrmqlly** [comment]
Also remove ./vscode/* files & folder

**Comment by g9aerospace** [comment]
ok now?

**Pull request merged**
